### ISSUE TITLE
【Windows实现定时自动锁屏】小小改进建议~

### ISSUE THREAD

**Issue by qq8-------6** [cofcool/cofcool.github.io#1]
可以不需要写那个可执行程序，可以直接使用rundll32命令调用user32.dll中的锁屏API函数

**Comment by cofcool** [comment]
似乎不可以，没有入口函数的话无法运行起来

**Comment by qq8-------6** [comment]
> 似乎不可以，没有入口函数的话无法运行起来

可以的，rundll32本来就是个Windows自带的可执行exe，可以方便的调用这些API函数，对于这个例子，可以直接让计划任务定时执行以下命令：
%windir%\system32\rundll32.exe user32.dll,LockWorkStation

**Comment by qq8-------6** [comment]
> > 似乎不可以，没有入口函数的话无法运行起来
> 
> 可以的，rundll32本来就是个Windows自带的可执行exe，可以方便的调用这些API函数，对于这个例子，可以直接让计划任务定时执行以下命令：
> %windir%\system32\rundll32.exe user32.dll,LockWorkStation

我这边在命令行窗口中手动执行这个命令，可以立即锁屏

**Comment by cofcool** [comment]
这样的话确实方便不少👍
